# Generated by Django 5.2.4 on 2025-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
